// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_frYPWkA1yH5mcfRirE96ZuE4boxSTtc',
    appId: '1:910812833637:web:88c3c98af361a3709ea38c',
    messagingSenderId: '910812833637',
    projectId: 'fir-ai-app-c68ff',
    authDomain: 'fir-ai-app-c68ff.firebaseapp.com',
    storageBucket: 'fir-ai-app-c68ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrlGRmkTFQKE3kolgkSZ0QDdEMPQ24_uY',
    appId: '1:910812833637:android:8fa532695d3616bd9ea38c',
    messagingSenderId: '910812833637',
    projectId: 'fir-ai-app-c68ff',
    storageBucket: 'fir-ai-app-c68ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLww0HOJ0bgVA_zIobr48y2NCEj1wqH4A',
    appId: '1:910812833637:ios:474b26bceb3d39c19ea38c',
    messagingSenderId: '910812833637',
    projectId: 'fir-ai-app-c68ff',
    storageBucket: 'fir-ai-app-c68ff.firebasestorage.app',
    androidClientId: '910812833637-oc3phpim3lejha7vsmjj77itfj3jkcfe.apps.googleusercontent.com',
    iosClientId: '910812833637-2amc103r5l3ca4ph0ekvl1p0a5cluto5.apps.googleusercontent.com',
    iosBundleId: 'com.sonduong.imageGeneratorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLww0HOJ0bgVA_zIobr48y2NCEj1wqH4A',
    appId: '1:910812833637:ios:474b26bceb3d39c19ea38c',
    messagingSenderId: '910812833637',
    projectId: 'fir-ai-app-c68ff',
    storageBucket: 'fir-ai-app-c68ff.firebasestorage.app',
    androidClientId: '910812833637-oc3phpim3lejha7vsmjj77itfj3jkcfe.apps.googleusercontent.com',
    iosClientId: '910812833637-2amc103r5l3ca4ph0ekvl1p0a5cluto5.apps.googleusercontent.com',
    iosBundleId: 'com.sonduong.imageGeneratorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_frYPWkA1yH5mcfRirE96ZuE4boxSTtc',
    appId: '1:910812833637:web:8f29094cd45b58739ea38c',
    messagingSenderId: '910812833637',
    projectId: 'fir-ai-app-c68ff',
    authDomain: 'fir-ai-app-c68ff.firebaseapp.com',
    storageBucket: 'fir-ai-app-c68ff.firebasestorage.app',
  );
}
